In [12]:
import pandas as pd
from fetch_data.config import config
import numpy as np

# Carregar os dados

In [21]:
df = pd.read_csv(os.path.join(config.DATA_RAW_PROCESS, 'data.csv'))

In [3]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,...,seller_city,seller_state,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,credit_card,...,maua,SP,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,3,voucher,...,maua,SP,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2,voucher,...,maua,SP,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
3,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,delivered,2017-08-15 18:29:31,2017-08-15 20:05:16,2017-08-17 15:28:33,2017-08-18 14:44:43,2017-08-28 00:00:00,1,credit_card,...,maua,SP,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
4,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,delivered,2017-08-02 18:24:47,2017-08-02 18:43:15,2017-08-04 17:35:43,2017-08-07 18:30:01,2017-08-15 00:00:00,1,credit_card,...,maua,SP,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0

In [4]:
df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'payment_sequential', 'payment_type', 'payment_installments',
       'payment_value', 'review_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp', 'customer_unique_id',
       'customer_zip_code_prefix', 'customer_city', 'customer_state',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'seller_zip_code_prefix', 'seller_city',
       'seller_state', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [5]:
df[['order_id','payment_type','product_id', 'product_category_name','price', 'freight_value', 'payment_installments','payment_value','review_comment_message']]

,order_id,payment_type,product_id,product_category_name,price,freight_value,payment_installments,payment_value,review_comment_message
0,e481f51cbdc54678b7cc49136f2d6af7,credit_card,87285b34884572647811a353c7ac498a,utilidades_domesticas,29.99,8.72,1,18.12,"Não testei o produto ainda, mas ele veio corre..."
1,e481f51cbdc54678b7cc49136f2d6af7,voucher,87285b34884572647811a353c7ac498a,utilidades_domesticas,29.99,8.72,1,2.00,"Não testei o produto ainda, mas ele veio corre..."
2,e481f51cbdc54678b7cc49136f2d6af7,voucher,87285b34884572647811a353c7ac498a,utilidades_domesticas,29.99,8.72,1,18.59,"Não testei o produto ainda, mas ele veio corre..."
3,128e10d95713541c87cd1a2e48201934,credit_card,87285b34884572647811a353c7ac498a,utilidades_domesticas,29.99,7.78,3,37.77,Deveriam embalar melhor o produto. A caixa vei...
4,0e7e841ddf8f8f2de2bad69267ecfbcf,credit_card,87285b34884572647811a353c7ac498a,utilidades_domesticas,29.99,7.78,1,37.77,"Só achei ela pequena pra seis xícaras ,mais é ..."
...,...,...,...,...,...,...,...,...,...
118310,1ab38815794efa43d269d62b98dae815,boleto,31ec3a565e06de4bdf9d2a511b822b4d,construcao_ferramentas_iluminacao,79.00,14.13,1,93.13,NaN
118311,b159d0ce7cd881052da94fa165617b05,credit_card,241a1ffc9cf969b27de6e72301020268,automotivo,19.70,10.96,1,30.66,NaN
118312,735dce2d574afe8eb87e80a3d6229c48,debit_card,1d187e8e7a30417fda31e85679d96f0f,moveis_decoracao,399.00,45.07,1,444.07,NaN
118313,25d2bfa43663a23586afd12f15b542e7,credit_card,6e1c2008dea1929b9b6c27fa01381e90,moveis_decoracao,219.90,24.12,4,244.02,NaN
118314,1565f22aa9452ff278638e87cc895678,boleto,9c1e194db1d35a79d962ea610bfe0868,perfumaria,15.50,12.79,1,28.29,NaN

# Data cleaning

In [22]:
df.isnull().sum()

order_id                              0
customer_id                           0
order_status                          0
order_purchase_timestamp              0
order_approved_at                    15
order_delivered_carrier_date       1254
order_delivered_customer_date      2588
order_estimated_delivery_date         0
payment_sequential                    0
payment_type                          0
payment_installments                  0
payment_value                         0
review_id                             0
review_score                          0
review_comment_title             104226
review_comment_message            67650
review_creation_date                  0
review_answer_timestamp               0
customer_unique_id                    0
customer_zip_code_prefix              0
customer_city                         0
customer_state                        0
order_item_id                         0
product_id                            0
seller_id                             0
shipping_limit_date                   0
price                                 0
freight_value                         0
seller_zip_code_prefix                0
seller_city                           0
seller_state                          0
product_category_name              1709
product_name_lenght                1709
product_description_lenght         1709
product_photos_qty                 1709
product_weight_g                     20
product_length_cm                    20
product_height_cm                    20
product_width_cm                     20
dtype: int64

In [23]:
df.drop(['review_comment_title', 'review_comment_message'], axis = 1, inplace = True)

In [24]:
df.dropna(inplace = True)

In [26]:
df.shape

(114073, 37)

# Hipoteses
- Clientes que não tiveram as suas entregas feita na hora não voltam a comprar
- Clientes de SP são os que tenho o maior volume de compra
- Clientes que compram com cartão de crédito compra mais que do que aqueles que compram com boleto
- Clientes que compram produtos leves compram em maior quantidade
- Clientes que tiveram as suas compras canceladas não voltam a comprar
- Clientes que um alto valor de frete compram diversos produtos
- Categoria do produto mais vendido é aquela relacionada a eletrônicos
- Somente 30% das categorias do produto representam 80% da receita da empresa (levando em consideração uma taxa de 15% por cada venda)
- Produtos que passaram do limite de envio são pouco vendido
- Vendedores de SP são os que mais atrasam os envios 
- Os tops vendedores representam a maioria dos produtos vendidos

In [1]:
df.product_category_name.unique()

NameError: name 'df' is not defined